/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package library;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class RetunBook extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rst = null;
    Object issuedid = null;
    String book_code = null;
    String[] cmbissue = {};
    String issueid = "";

    /** Creates new form RetunBook */
    public RetunBook() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try
        {
            Connection con=null;
            PreparedStatement ps=null;
            ResultSet rs=null;
            con=connection.connect.makeConnection();
            ps=con.prepareStatement("select issue_id from book_issue where status='true'");
            rs=ps.executeQuery();
            while(rs.next())
            {
                issueid=issueid+rs.getString(1)+":-";
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        cmbissue = issueid.split(":-");
        cmbIssuedID = new javax.swing.JComboBox(cmbissue);
        jLabel3 = new javax.swing.JLabel();
        txtbook_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtbookname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstuid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtstuname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtissuedate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtreturndate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Book Return");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BOOK RETURN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Book Issued ID");

        cmbIssuedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIssuedIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Book Code");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Book Name");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Student ID");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Student Name");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Issued Date");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Return Date");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbIssuedID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbook_code)
                            .addComponent(txtbookname)
                            .addComponent(txtstuid)
                            .addComponent(txtstuname)
                            .addComponent(txtissuedate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtreturndate, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtbook_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtbookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtstuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtstuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtissuedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtreturndate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(cmbIssuedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        menu mn = new menu();
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbIssuedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIssuedIDActionPerformed
        // TODO add your handling code here:
        issuedid = cmbIssuedID.getSelectedItem();
        try {
            con = connection.connect.makeConnection();
            Statement st = con.createStatement();
            String query = "select book_code,book_name,student_id,student_name,DATE_FORMAT(issue_date, '%D %M %Y'),DATE_FORMAT(curdate(), '%D %M %Y') from book_issue where issue_id='" + issuedid.toString() + "'";
            rst = st.executeQuery(query);
            if (rst.next()) {
                txtbook_code.setText(rst.getString(1));
                txtbookname.setText(rst.getString(2));
                txtstuid.setText(rst.getString(3));
                txtstuname.setText(rst.getString(4));
                txtissuedate.setText(rst.getString(5));
                txtreturndate.setText(rst.getString(6));
            } else {
                JOptionPane.showMessageDialog(null, "Data Not Found!!");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbIssuedIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        issuedid = cmbIssuedID.getSelectedItem();
        if (issuedid.equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select Book Issue ID!!");
            return;
        }
        book_code = txtbook_code.getText();

        if (!issuedid.equals("")) {
            try {
                con = connection.connect.makeConnection();
                pst = con.prepareStatement("update book_issue set status='false' where issue_id='" + issuedid.toString() + "'");
                int i = pst.executeUpdate();
                if (i > 0) {
                    // Increase Update Quantiy
                    updateBookQuantity(book_code);
                    JOptionPane.showMessageDialog(null, "Return Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Return Canceled");
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RetunBook().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbIssuedID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtbook_code;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtreturndate;
    private javax.swing.JTextField txtstuid;
    private javax.swing.JTextField txtstuname;
    // End of variables declaration//GEN-END:variables

//Increase Book quantity
    public void updateBookQuantity(String boookid) {

        int res, qty = 0;
        try {
            Connection con11 = connection.connect.makeConnection();
            Statement st11 = con11.createStatement();
            String query = "select quantity from book_master where book_code='" + boookid + "'";
            ResultSet rst11 = st11.executeQuery(query);
            if (rst11.next()) {
                res = rst11.getInt(1);
                qty = res + 1;
                try {
                    Connection con22 = connection.connect.makeConnection();
                    PreparedStatement pstt = con22.prepareStatement("update book_master set quantity='" + qty + "' where book_code='" + boookid + "'");
                    pstt.executeUpdate();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            st11.close();
            con11.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}
